output the file path in report
gemini-testing/hermione-allure-reporter pull request #16
Opened 2016-09-21 06:13 UTC by DudaGod

2016-09-21 06:17 UTC, DudaGod commented
![2016-09-21_09-14-15](https://cloud.githubusercontent.com/assets/5900697/18699810/3ae9a600-7fdc-11e6-8ed0-4692c11d639d.png)

2016-09-21 08:07 UTC, tormozz48 approved these changes
🆗

2016-09-21 08:10 UTC, sipayRT commented
обрежь путь до относительного

2016-09-21 08:57 UTC, DudaGod commented
![2016-09-21_11-56-45](https://cloud.githubusercontent.com/assets/5900697/18704435/8df07458-7ff2-11e6-8410-0ac1744a98bf.png)

2016-09-21 09:00 UTC, eGavr commented
а не сильно ли ты обрезал? относительный путь не с `web4` должен начинаться?

2016-09-21 09:01 UTC, eGavr commented on lib/suite-adapter.js
> +        const relativeFilePath = _.isString(mochaTest.file)
в каких случаях `mochaTest.file` может быть не строкой?

2016-09-21 09:03 UTC, eGavr commented on lib/suite-adapter.js
> +            ? mochaTest.file.replace(process.cwd(), '')
```
path.relative(process.cwd(), mochaTest.file)
```

2016-09-21 09:04 UTC, eGavr commented
/ok

Но все еще интересно, когда `mochaTest.file` может быть не строкой

2016-09-21 11:08 UTC, DudaGod commented
Да, наверно должен с web4 стартовать, исправил.
По поводу 2го вопроса, думаю что никогда. Исправил просто на проверку, что поле file имеется в объекте mochaTest.

2016-09-21 11:09 UTC, DudaGod commented
![2016-09-21_13-59-58](https://cloud.githubusercontent.com/assets/5900697/18708737/03aade1a-8005-11e6-97f8-aea06f27cf60.png)

2016-09-28 17:41 UTC, DudaGod commented
/cc @j0tunn @sipayRT @rostik404

2016-09-29 12:04 UTC, sipayRT commented
В описание добавь актуальный скриншот, поправь путь
В остальном ок

2016-09-30 07:22 UTC, sipayRT requested changes

2016-09-30 07:22 UTC, sipayRT commented on lib/suite-adapter.js
> +            ? path.relative(path.resolve(process.cwd(), '..'), mochaTest.file)
а зачем нам тут имя корневой директории? `path.relative(process.cwd(), mochaTest.file)` будет намного удобнее и правильнее

2016-09-30 07:22 UTC, sipayRT commented on lib/suite-adapter.js
> +            ? path.relative(path.resolve(process.cwd(), '..'), mochaTest.file)
кстати ,при каких условиях у моки может не быть ключа `file`? если мока сформировала объект теста, то там при любых условиях будет путь к файлу, т.к. она по этому пути тест и распарсила

2016-09-30 07:26 UTC, DudaGod commented on lib/suite-adapter.js
> +            ? path.relative(path.resolve(process.cwd(), '..'), mochaTest.file)
По поводу корневой директории - я это уже исправил в последнем коммите. Когда пустой может быть не исследовал, просто на всякий случай поставил, чтобы ничего не взорвалось.

2016-09-30 07:27 UTC, DudaGod commented
Так там уже актуальный! И путь исправлен

2016-09-30 09:12 UTC, sipayRT approved these changes

2016-09-30 13:19 UTC, merged